/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;
import cont.*;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author eater48
 */
public class Entry_anggota extends javax.swing.JFrame {

    /**
     * Creates new form entry_anggota
     */
    public Entry_anggota() {
        initComponents();
        table_value();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jrs = new javax.swing.JComboBox<>();
        id = new javax.swing.JTextField();
        kode = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        tlp = new javax.swing.JTextField();
        almt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        nw = new javax.swing.JButton();
        sv = new javax.swing.JButton();
        up = new javax.swing.JButton();
        del = new javax.swing.JButton();
        set = new javax.swing.JButton();
        ext = new javax.swing.JButton();
        err = new javax.swing.JLabel();
        no = new javax.swing.JComboBox<>();
        kls = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        dt = new javax.swing.JMenu();
        hm = new javax.swing.JMenuItem();
        ang = new javax.swing.JMenuItem();
        rak = new javax.swing.JMenuItem();
        pinjam = new javax.swing.JMenu();
        lapor = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(480, 480));
        setMinimumSize(new java.awt.Dimension(892, 573));
        setPreferredSize(new java.awt.Dimension(892, 573));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rajibhaha.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ENTRY ANGGOTA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel3.setText("Perpustakaan SMKN 2 Kota Mojokerto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel4.setText("ID Anggota");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel5.setText("Kode Anggota");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setText("Nama Anggota");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel7.setText("Jurusan Anggota");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel8.setText("No Telepon");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel9.setText("Alamat");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jrs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "APHP", "DKV", "Kuliner", "LPS", "RPL" }));
        getContentPane().add(jrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 80, -1));

        id.setEditable(false);
        id.setToolTipText("AUTO");
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 200, -1));
        getContentPane().add(kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 200, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 200, -1));
        getContentPane().add(tlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 200, -1));
        getContentPane().add(almt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 200, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Anggota", "Kode Anggota", "Nama Anggota", "Jurusan Anggota", "No Tlp", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 480, 260));

        nw.setText("New");
        nw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nwActionPerformed(evt);
            }
        });
        getContentPane().add(nw, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 80, -1));

        sv.setText("Simpan");
        sv.setEnabled(false);
        sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svActionPerformed(evt);
            }
        });
        getContentPane().add(sv, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 80, -1));

        up.setText("Update");
        up.setEnabled(false);
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        getContentPane().add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 80, -1));

        del.setText("Delete");
        del.setEnabled(false);
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 80, -1));

        set.setText("Reset");
        set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActionPerformed(evt);
            }
        });
        getContentPane().add(set, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, 80, -1));

        ext.setText("Exit");
        ext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extActionPerformed(evt);
            }
        });
        getContentPane().add(ext, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 80, -1));
        getContentPane().add(err, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 50, -1));

        kls.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "XI", "XII" }));
        getContentPane().add(kls, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 50, -1));

        dt.setText("Data");

        hm.setText("Home");
        hm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hmActionPerformed(evt);
            }
        });
        dt.add(hm);

        ang.setText("Angoota");
        ang.setEnabled(false);
        ang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angActionPerformed(evt);
            }
        });
        dt.add(ang);

        rak.setText("Rak Buku");
        rak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rakActionPerformed(evt);
            }
        });
        dt.add(rak);

        jMenuBar1.add(dt);

        pinjam.setText("Peminjaman");
        jMenuBar1.add(pinjam);

        lapor.setText("Laporan");
        jMenuBar1.add(lapor);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void table_value(){
        cont c = new cont();
        
        try {
            DefaultTableModel dt = (DefaultTableModel) table.getModel();
            dt.setRowCount(0);
            Class.forName(c.JD);
            c.cont = DriverManager.getConnection(c.DB);
            c.stm = c.cont.createStatement();
            String show = "SELECT*FROM APP.anggota";
            c.rs = c.stm.executeQuery(show);
            
            while (c.rs.next()) {
                Vector v = new Vector();
                v.add(c.rs.getString(1));
                v.add(c.rs.getString(2));
                v.add(c.rs.getString(3));
                v.add(c.rs.getString(4));
                v.add(c.rs.getString(5));
                v.add(c.rs.getString(6));
                
                dt.addRow(v);
            }
            c.stm.close();c.cont.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
        cont c = new cont();
        try {
            Class.forName(c.JD);
            c.cont = DriverManager.getConnection(c.DB);
            c.stm = c.cont.createStatement();
            String in= "SELECT*FROM APP.anggota WHERE id_anggota='"+id.getText()+"'";
            
            c.rs = c.stm.executeQuery(in);
            if (c.rs.next()) {
               kode.setText(c.rs.getString("kode_anggota"));
               nama.setText(c.rs.getString("nama_anggota"));
               try {
                    String sp = c.rs.getString("jurusan_anggota");
            String[] ary = sp.split(" ",3);
            int k=0,j=0,nu=0;
            
                if (ary[0].equals("X")) {
                    k = 0;
                }else if (ary[0].equals("XI")) {
                    k = 1;
                }else if (ary[0].equals("XII")) {
                    k = 2;
                }
                if (ary[1].equals("APHP")) {
                    j = 0;
                }else if (ary[1].equals("DKV")) {
                    j = 1;
                }else if (ary[1].equals("Kuliner")) {
                    j = 2;
                }else if (ary[1].equals("LPS")) {
                    j = 3;
                }else if (ary[1].equals("RPL")) {
                    j = 4;
                }
                if (ary[2].equals("1")) {
                    nu = 0;
                }else if (ary[2].equals("2")) {
                    nu = 1;
                }else if (ary[2].equals("3")) {
                    nu = 2;
                }
            
            kls.setSelectedIndex(k);jrs.setSelectedIndex(j);no.setSelectedIndex(nu);
                } catch (Exception e) {
                    e.printStackTrace();
                }
               tlp.setText("no_telp_anggota");
               almt.setText("alamat_anggota");
            }
            c.stm.close();c.cont.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        table_value();
    }//GEN-LAST:event_idActionPerformed

    private void nwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nwActionPerformed
        // TODO add your handling code here:
        id.setText("Auto");
        kode.setText("");
        nama.setText("");
        kls.setSelectedIndex(0);kls.setSelectedIndex(0);no.setSelectedIndex(0);
        tlp.setText("");
        almt.setText("");
        sv.setEnabled(true);
        set.setEnabled(true);
        table_value();
    }//GEN-LAST:event_nwActionPerformed

    private void setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setActionPerformed
        // TODO add your handling code here:
        id.setText("");
        kode.setText("");
        nama.setText("");
        kls.setSelectedIndex(0);kls.setSelectedIndex(0);no.setSelectedIndex(0);
        tlp.setText("");
        almt.setText("");
        sv.setEnabled(false);
        set.setEnabled(false);
        up.setEnabled(false);
        del.setEnabled(false);
        nw.setEnabled(true);
        table_value();
    }//GEN-LAST:event_setActionPerformed

    private void svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svActionPerformed
        // TODO add your handling code here:
        cont c = new cont();
        try {
            Class.forName(c.JD);
            c.cont = DriverManager.getConnection(c.DB);
            c.stm = c.cont.createStatement();
            String in= "INSERT INTO APP.anggota(kode_anggota,nama_anggota,jurusan_anggota,no_telp_anggota,alamat_anggota) VALUES('"
                    +kode.getText()+"','"
                    +nama.getText()+"','"
                    +kls.getSelectedItem().toString()+" "+jrs.getSelectedItem().toString()+" "+no.getSelectedItem()+"','"
                    +tlp.getText()+"','"
                    +almt.getText()+"'"
                    +")";
            c.stm.executeUpdate(in);
            c.stm.close();c.cont.close();
        } catch (Exception e) {
            e.printStackTrace();
            err.setText("Error Saat Memasukkan Data!");
        }
        table_value();
        sv.setEnabled(false);
        set.setEnabled(false);
        del.setEnabled(false);
        up.setEnabled(false);
        table_value();
    }//GEN-LAST:event_svActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
         cont c = new cont();
        try {
            Class.forName(c.JD);
            c.cont = DriverManager.getConnection(c.DB);
            c.stm = c.cont.createStatement();
            String del= "DELETE FROM APP.anggota WHERE id_anggota="+id.getText()+"";
            
            err.setText("Data Berhasil Dihapus!");
            
            c.stm.executeUpdate(del);
            
            c.stm.close();c.cont.close();
        } catch (Exception e) {
            e.printStackTrace();
            err.setText("Data Gagal Dihapus!");
        }
        id.setText("");
        kode.setText("");
        nama.setText("");
        kls.setSelectedIndex(0);kls.setSelectedIndex(0);no.setSelectedIndex(0);
        tlp.setText("");
        almt.setText("");
        set.setEnabled(false);
        up.setEnabled(false);
        del.setEnabled(false);
        nw.setEnabled(true);
        table_value();
    }//GEN-LAST:event_delActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        cont c = new cont();
        
        int[] td = table.getSelectedRows();
        int n = 0;
        for(int dt : td){
        n = 10*n+dt;
        }
        id.setText(table.getValueAt(n, 0).toString());
        kode.setText(table.getValueAt(n, 1).toString());
        nama.setText(table.getValueAt(n, 2).toString());
        tlp.setText(table.getValueAt(n, 4).toString());
        almt.setText(table.getValueAt(n, 5).toString());
        
        up.setEnabled(true);
        del.setEnabled(true);
        nw.setEnabled(false);
        set.setEnabled(true);
        
                try {
                    String sp = table.getValueAt(n, 3).toString();
            String[] ary = sp.split(" ",3);
            int k=0,j=0,nu=0;
            
                if (ary[0].equals("X")) {
                    k = 0;
                }else if (ary[0].equals("XI")) {
                    k = 1;
                }else if (ary[0].equals("XII")) {
                    k = 2;
                }
                if (ary[1].equals("APHP")) {
                    j = 0;
                }else if (ary[1].equals("DKV")) {
                    j = 1;
                }else if (ary[1].equals("Kuliner")) {
                    j = 2;
                }else if (ary[1].equals("LPS")) {
                    j = 3;
                }else if (ary[1].equals("RPL")) {
                    j = 4;
                }
                if (ary[2].equals("1")) {
                    nu = 0;
                }else if (ary[2].equals("2")) {
                    nu = 1;
                }else if (ary[2].equals("3")) {
                    nu = 2;
                }
            
            kls.setSelectedIndex(k);jrs.setSelectedIndex(j);no.setSelectedIndex(nu);
            
                } catch (Exception e) {
                    e.printStackTrace();
                }
                   
    }//GEN-LAST:event_tableMouseClicked

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        // TODO add your handling code here:
        cont c = new cont();
        
        try {
            Class.forName(c.JD);
            c.cont = DriverManager.getConnection(c.DB);
            c.stm = c.cont.createStatement();
             String up = "UPDATE APP.anggota SET kode_anggota='"+kode.getText()+"',nama_anggota='"
                     +nama.getText()+"',jurusan_anggota='"+kls.getSelectedItem().toString()+" "+jrs.getSelectedItem().toString()+" "+no.getSelectedItem()
                     +"',no_telp_anggota='"+tlp.getText()+"',alamat_anggota='"+almt.getText()+"' WHERE id_anggota="+id.getText()+"";
             c.stm.executeUpdate(up);
             err.setText("Suksess Update Data!");
        } catch (Exception e) {
            e.printStackTrace();
            err.setText("Gagal Update Data!");
        }
        table_value();
    }//GEN-LAST:event_upActionPerformed

    private void extActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_extActionPerformed

    private void angActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angActionPerformed

    private void hmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hmActionPerformed
        // TODO add your handling code here:
        root r = new root();
        r.Tohome();
        this.dispose();
    }//GEN-LAST:event_hmActionPerformed

    private void rakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rakActionPerformed
        // TODO add your handling code here:
        root r = new root();
        r.Torak();
        this.dispose();
    }//GEN-LAST:event_rakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entry_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entry_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entry_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entry_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entry_anggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField almt;
    private javax.swing.JMenuItem ang;
    private javax.swing.JButton del;
    private javax.swing.JMenu dt;
    private javax.swing.JLabel err;
    private javax.swing.JButton ext;
    private javax.swing.JMenuItem hm;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jrs;
    private javax.swing.JComboBox<String> kls;
    private javax.swing.JTextField kode;
    private javax.swing.JMenu lapor;
    private javax.swing.JTextField nama;
    private javax.swing.JComboBox<String> no;
    private javax.swing.JButton nw;
    private javax.swing.JMenu pinjam;
    private javax.swing.JMenuItem rak;
    private javax.swing.JButton set;
    private javax.swing.JButton sv;
    private javax.swing.JTable table;
    private javax.swing.JTextField tlp;
    private javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables
}
