/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;
import cont.*;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eater48
 */
public class Rak extends javax.swing.JFrame {

    /**
     * Creates new form Rak
     */
    public Rak() {
        initComponents();
        table_value();
        
    }
    private void table_value(){
        cont c = new cont();
        
        try {
            DefaultTableModel dt = (DefaultTableModel) table.getModel();
            dt.setRowCount(0);
            Class.forName(c.JD);
            c.cont = DriverManager.getConnection(c.DB);
            c.stm = c.cont.createStatement();
            String show = "SELECT*FROM APP.rak";
            c.rs = c.stm.executeQuery(show);
            
            while (c.rs.next()) {
                Vector v = new Vector();
                v.add(c.rs.getString(1));
                v.add(c.rs.getString(2));
                
                dt.addRow(v);
            }
            c.stm.close();c.cont.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nw = new javax.swing.JButton();
        sv = new javax.swing.JButton();
        up = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        set = new javax.swing.JButton();
        ext = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        err = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        dt = new javax.swing.JMenu();
        hm = new javax.swing.JMenuItem();
        ang = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        pinjam = new javax.swing.JMenu();
        lapor = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(479, 618));
        setPreferredSize(new java.awt.Dimension(479, 618));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rajibhaha.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ENTRY Rak Buku");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel3.setText("Perpustakaan SMKN 2 Kota Mojokerto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        nw.setText("New");
        nw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nwActionPerformed(evt);
            }
        });
        getContentPane().add(nw, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 80, -1));

        sv.setText("Simpan");
        sv.setEnabled(false);
        sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svActionPerformed(evt);
            }
        });
        getContentPane().add(sv, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 80, -1));

        up.setText("Update");
        up.setEnabled(false);
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        getContentPane().add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 80, -1));

        del.setText("Delete");
        del.setEnabled(false);
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 80, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Rak", "Rak Buku"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 220, 300));

        set.setText("Reset");
        set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActionPerformed(evt);
            }
        });
        getContentPane().add(set, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 80, -1));

        ext.setText("Exit");
        ext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extActionPerformed(evt);
            }
        });
        getContentPane().add(ext, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 80, -1));

        jLabel4.setText("ID Rak");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        id.setEditable(false);
        id.setToolTipText("AUTO");
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 200, -1));

        jLabel5.setText("Nama Rak");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 200, -1));
        getContentPane().add(err, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        dt.setText("Data");

        hm.setText("Home");
        hm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hmActionPerformed(evt);
            }
        });
        dt.add(hm);

        ang.setText("Angoota");
        ang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angActionPerformed(evt);
            }
        });
        dt.add(ang);

        jMenuItem1.setText("Rak Buku");
        jMenuItem1.setEnabled(false);
        dt.add(jMenuItem1);

        jMenuBar1.add(dt);

        pinjam.setText("Peminjaman");
        jMenuBar1.add(pinjam);

        lapor.setText("Laporan");
        jMenuBar1.add(lapor);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hmActionPerformed
        // TODO add your handling code here:
        root r = new root();
        r.Tohome();
        this.dispose();
    }//GEN-LAST:event_hmActionPerformed

    private void angActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angActionPerformed
        // TODO add your handling code here:
        root r = new root();
        r.Toentry();
        this.dispose();
    }//GEN-LAST:event_angActionPerformed

    private void nwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nwActionPerformed
        // TODO add your handling code here:
        id.setText("Auto");
        name.setText("");
        
        sv.setEnabled(true);
        set.setEnabled(true);
        del.setEnabled(false);
        up.setEnabled(false);
        table_value();
    }//GEN-LAST:event_nwActionPerformed

    private void svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svActionPerformed
        // TODO add your handling code here:
        cont c = new cont();
        try {
            Class.forName(c.JD);
            c.cont = DriverManager.getConnection(c.DB);
            c.stm = c.cont.createStatement();
            String in= "INSERT INTO APP.rak(nama_rak) VALUES('"
            +name.getText()+"'"
            +")";
            c.stm.executeUpdate(in);
            c.stm.close();c.cont.close();
        } catch (Exception e) {
            e.printStackTrace();
            err.setText("Error Saat Memasukkan Data!");
        }
        table_value();
        sv.setEnabled(false);
        set.setEnabled(false);
        del.setEnabled(false);
        up.setEnabled(false);
        table_value();
    }//GEN-LAST:event_svActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        // TODO add your handling code here:
        cont c = new cont();

        try {
            Class.forName(c.JD);
            c.cont = DriverManager.getConnection(c.DB);
            c.stm = c.cont.createStatement();
            String up = "UPDATE APP.rak SET nama_rak='"+name.getText()+"' WHERE id_rak="+id.getText()+"";
            c.stm.executeUpdate(up);
            err.setText("Suksess Update Data!");
        } catch (Exception e) {
            e.printStackTrace();
            err.setText("Gagal Update Data!");
        }
        table_value();
    }//GEN-LAST:event_upActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        cont c = new cont();
        try {
            Class.forName(c.JD);
            c.cont = DriverManager.getConnection(c.DB);
            c.stm = c.cont.createStatement();
            String del= "DELETE FROM APP.rak WHERE id_rak="+id.getText()+"";

            err.setText("Data Berhasil Dihapus!");

            c.stm.executeUpdate(del);

            c.stm.close();c.cont.close();
        } catch (Exception e) {
            e.printStackTrace();
            err.setText("Data Gagal Dihapus!");
        }
        id.setText("");
        name.setText("");
        set.setEnabled(false);
        up.setEnabled(false);
        del.setEnabled(false);
        nw.setEnabled(true);
        table_value();
    }//GEN-LAST:event_delActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        cont c = new cont();

        int[] td = table.getSelectedRows();
        int n = 0;
        for(int dt : td){
            n = 10*n+dt;
        }
        id.setText(table.getValueAt(n, 0).toString());
        name.setText(table.getValueAt(n, 1).toString());

        up.setEnabled(true);
        del.setEnabled(true);
        nw.setEnabled(false);
        set.setEnabled(true);

       

    }//GEN-LAST:event_tableMouseClicked

    private void setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setActionPerformed
        // TODO add your handling code here:
        id.setText("");
        name.setText("");
        sv.setEnabled(false);
        set.setEnabled(false);
        up.setEnabled(false);
        del.setEnabled(false);
        nw.setEnabled(true);
        table_value();
    }//GEN-LAST:event_setActionPerformed

    private void extActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_extActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
        cont c = new cont();
        try {
            Class.forName(c.JD);
            c.cont = DriverManager.getConnection(c.DB);
            c.stm = c.cont.createStatement();
            String in= "SELECT*FROM APP.rak WHERE id_rak='"+id.getText()+"'";

            c.rs = c.stm.executeQuery(in);
            if (c.rs.next()) {
                name.setText(c.rs.getString("nama_rak"));  
            }
            c.stm.close();c.cont.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        table_value();
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ang;
    private javax.swing.JButton del;
    private javax.swing.JMenu dt;
    private javax.swing.JLabel err;
    private javax.swing.JButton ext;
    private javax.swing.JMenuItem hm;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu lapor;
    private javax.swing.JTextField name;
    private javax.swing.JButton nw;
    private javax.swing.JMenu pinjam;
    private javax.swing.JButton set;
    private javax.swing.JButton sv;
    private javax.swing.JTable table;
    private javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables
}
